export type ResponseShape = "data_rows" | "data_object" | "nested_rows" | "top_level_rows" | "top_level_object" | "balances_map";

export interface CommandContract {
  command: string;
  method: string;
  path: string;
  scope: string;
  paginates: boolean;
  shape: ResponseShape;
  rowPath: string;
  fields: string[];
  defaultFields: string[];
  topLevelKeys: string[];
  description: string;
}

export const CONTRACTS: CommandContract[] = [
  { command: "sales list", method: "POST", path: "/v1/sales", scope: "orders:read", paginates: true, shape: "data_rows", rowPath: "data", fields: ["customer","id","items","itemsCount","orderDate","orderNumber","paymentMethod","status","totalAmount"], defaultFields: ["id","status","totalAmount","orderDate"], topLevelKeys: ["data","meta","pagination","success"], description: "Lista ordenes con estado, fecha, pago, cliente, items y total." },
  { command: "sales metrics", method: "POST", path: "/v1/sales/metrics", scope: "orders:read", paginates: false, shape: "data_object", rowPath: "data", fields: ["avgTicket","cancelledOrders","completedOrders","pendingOrders","totalOrders","totalSales"], defaultFields: ["data","meta","success"], topLevelKeys: ["data","meta","success"], description: "Metricas agregadas de ventas por periodo y agrupaciones." },
  { command: "sales detail", method: "POST", path: "/v1/sales/detail", scope: "orders:read", paginates: false, shape: "data_object", rowPath: "data", fields: ["customer","id","items","orderDate","orderNumber","paymentMethod","status","totalAmount"], defaultFields: ["data","meta","success"], topLevelKeys: ["data","meta","success"], description: "Detalle de una orden por UUID." },
  { command: "customers list", method: "POST", path: "/v1/customers", scope: "customers:read", paginates: true, shape: "data_rows", rowPath: "data", fields: ["avg_ticket","customer_id","last_order_date","name","order_count","phone","total_spent","waros_balance"], defaultFields: ["customer_id","name","order_count","total_spent"], topLevelKeys: ["data","limit","offset","total"], description: "Lista clientes con frecuencia, valor, ticket y saldo WAROS." },
  { command: "customers detail", method: "POST", path: "/v1/customers/detail", scope: "customers:read", paginates: false, shape: "data_object", rowPath: "data", fields: [], defaultFields: ["data","meta","success"], topLevelKeys: ["data","meta","success"], description: "Detalle e historial de un cliente." },
  { command: "customers orders", method: "POST", path: "/v1/customers/orders", scope: "customers:read", paginates: true, shape: "top_level_rows", rowPath: "items", fields: ["id","items","itemsCount","orderDate","orderNumber","paymentMethod","status","totalAmount"], defaultFields: ["id","orderNumber","totalAmount","orderDate"], topLevelKeys: ["items","limit","offset","total"], description: "Ordenes de un cliente por periodo." },
  { command: "customers metrics", method: "POST", path: "/v1/customers/metrics", scope: "customers:read", paginates: false, shape: "top_level_rows", rowPath: "top_customers", fields: ["customer_id","name","order_count","phone","total_spent"], defaultFields: ["summary","top_customers"], topLevelKeys: ["summary","top_customers"], description: "Resumen clientes nuevos vs recurrentes y top customers." },
  { command: "menu products", method: "POST", path: "/v1/menu/products", scope: "menu:read", paginates: true, shape: "data_rows", rowPath: "data", fields: ["allowModifiers","calculatedCost","category","description","id","ingredients","isAvailable","modifierGroups","name","perceivedCost","preparationTime","price","recipeBases"], defaultFields: ["id","name","price","isAvailable"], topLevelKeys: ["data","meta","pagination","success"], description: "Catalogo productos, precios, costos, recetas y disponibilidad." },
  { command: "menu recipes", method: "POST", path: "/v1/menu/recipes", scope: "menu:read", paginates: true, shape: "data_rows", rowPath: "data", fields: ["createdAt","description","id","ingredients","isActive","name","updatedAt"], defaultFields: ["id","name","isActive","ingredients"], topLevelKeys: ["data","meta","pagination","success"], description: "Recetas activas e ingredientes." },
  { command: "menu modifiers", method: "POST", path: "/v1/menu/modifiers", scope: "menu:read", paginates: true, shape: "data_rows", rowPath: "data", fields: ["associatedProducts","createdAt","id","isRequired","maxQty","minQty","modifiers","name","updatedAt"], defaultFields: ["id","name","isRequired","modifiers"], topLevelKeys: ["data","meta","pagination","success"], description: "Grupos de modificadores y productos asociados." },
  { command: "analytics menu", method: "POST", path: "/v1/analytics/menu-analysis", scope: "analytics:read", paginates: false, shape: "nested_rows", rowPath: "data.menu_items", fields: ["avg_price","category","classification","cost_used_for_classification","costo_percibido","estimated_cost","id","name","order_count","price","profit_margin_pct","profit_margin_real_pct","profit_per_unit","total_profit","total_revenue","total_units_sold"], defaultFields: ["data","success"], topLevelKeys: ["data","success"], description: "Performance menu por producto: unidades, ingresos, margen." },
  { command: "analytics food-cost", method: "POST", path: "/v1/analytics/food-cost", scope: "analytics:read", paginates: false, shape: "data_rows", rowPath: "data", fields: ["avg_price","category","classification","cost_used_for_classification","costo_percibido","estimated_cost","id","name","order_count","price","profit_margin_pct","profit_margin_real_pct","profit_per_unit","total_profit","total_revenue","total_units_sold"], defaultFields: ["data","meta","success"], topLevelKeys: ["data","meta","success"], description: "Food cost y margen por producto." },
  { command: "analytics alerts", method: "POST", path: "/v1/analytics/alerts", scope: "analytics:read", paginates: false, shape: "nested_rows", rowPath: "data.alerts", fields: ["action","description","id","title","type"], defaultFields: ["data","success"], topLevelKeys: ["data","success"], description: "Alertas analiticas y recomendaciones." },
  { command: "analytics data-quality", method: "POST", path: "/v1/analytics/data-quality", scope: "analytics:read", paginates: false, shape: "data_rows", rowPath: "data", fields: ["actual_value","alert_type","context","corrected_value","created_at","deviation_pct","expected_value","id","ingredient_id","ingredient_name","original_value","purchase_date","purchase_id","purchase_item_id","purchase_number","resolution_note","resolved","resolved_at","resolved_by","rolling_avg","severity","supplier_name","tenant_id"], defaultFields: ["data","meta","success"], topLevelKeys: ["data","meta","success"], description: "Alertas calidad de datos en compras e ingredientes." },
  { command: "analytics cohort", method: "POST", path: "/v1/analytics/cohort", scope: "analytics:read", paginates: false, shape: "data_rows", rowPath: "data", fields: ["cohort_date","cohort_label","cohort_size","retention"], defaultFields: ["data","success"], topLevelKeys: ["cohorts","period","periods"], description: "Matriz cohortes retencion semanal/mensual." },
  { command: "analytics waros", method: "POST", path: "/v1/analytics/waros", scope: "analytics:read", paginates: false, shape: "data_rows", rowPath: "data", fields: ["active_members","name","period","redemption_rate_pct","total_earned","total_issued","total_redeemed","transaction_count"], defaultFields: ["groups","summary"], topLevelKeys: ["groups","summary"], description: "Analitica WAROS: emitidos, redimidos, tasa." },
  { command: "analytics rfm", method: "POST", path: "/v1/analytics/rfm", scope: "analytics:read", paginates: false, shape: "data_rows", rowPath: "data", fields: ["customer_id","customer_name","f_score","last_order_date","m_score","order_count","r_score","segment","total_spent"], defaultFields: ["data"], topLevelKeys: ["data"], description: "Segmentacion RFM por recencia, frecuencia y valor." },
  { command: "analytics churn-risk", method: "POST", path: "/v1/analytics/churn-risk", scope: "analytics:read", paginates: false, shape: "data_rows", rowPath: "data", fields: ["avg_visit_interval_days","customer_id","days_since_last_order","lifetime_value","name","order_count","phone","risk_score"], defaultFields: ["customers","min_orders","threshold_multiplier","total_count"], topLevelKeys: ["customers","min_orders","threshold_multiplier","total_count"], description: "Clientes en riesgo churn por silencio." },
  { command: "financial products", method: "POST", path: "/v1/financial/products", scope: "financial:read", paginates: false, shape: "data_rows", rowPath: "data", fields: ["category","classification","cost","id","last_order_date","margin","name","order_count","price","profit","sales","tirImpact"], defaultFields: ["categories","filters","insights","metrics","products"], topLevelKeys: ["categories","filters","insights","metrics","products"], description: "Analisis financiero productos: margen, costo, ganancia." },
  { command: "waros estimate", method: "POST", path: "/v1/waros/estimate", scope: "waros:read", paginates: false, shape: "data_object", rowPath: "data", fields: ["earned","total","tier"], defaultFields: ["data","meta","success"], topLevelKeys: ["data","meta","success"], description: "Estimacion WAROS por compra." },
  { command: "waros balances", method: "POST", path: "/v1/waros/balances", scope: "waros:read", paginates: false, shape: "balances_map", rowPath: "balances", fields: ["profile_id","balance"], defaultFields: ["balances"], topLevelKeys: ["balances"], description: "Saldo WAROS para lista de perfiles." },
  { command: "waros customer", method: "POST", path: "/v1/waros/customer", scope: "waros:read", paginates: false, shape: "data_object", rowPath: "data", fields: ["balance","customer","profile_id","tier"], defaultFields: ["data","meta","success"], topLevelKeys: ["data","meta","success"], description: "Resumen WAROS de un cliente." },
  { command: "queries schema", method: "GET", path: "/v1/queries/schema", scope: "queries:read", paginates: false, shape: "data_rows", rowPath: "data", fields: ["default_limit","description","dimensions","filters","label","limitations","max_limit","measures","name","required_scope","sortable_fields"], defaultFields: ["data","success"], topLevelKeys: ["data","success"], description: "Lista datasets, dimensiones, medidas y filtros QuerySpec." },
  { command: "queries run", method: "POST", path: "/v1/queries/run", scope: "queries:read", paginates: false, shape: "data_rows", rowPath: "data", fields: ["avg_price","avg_ticket","category","classification","cost_source","customer","customer_id","day","ingredient","ingredient_id","unit","status","current_stock","minimum_stock","maximum_stock","unit_cost","stock_value","movement_type","reference_table","reference_number","quantity_in","quantity_out","net_quantity","movement_count","avg_cost_per_unit","supplier","supplier_id","purchase_number","is_direct_entry","quantity_purchased","quantity_received","total_cost","avg_unit_cost","purchase_count","last_order_date","order_count","orders_count","product","product_id","profit_margin_operativo_pct","profit_margin_pct","profit_margin_real_pct","profit_per_unit","quantity_sold","revenue","total_profit","total_spent","waros_balance"], defaultFields: ["data","success"], topLevelKeys: ["data","success"], description: "Ejecuta QuerySpec seguro y devuelve filas analiticas." },
];

export function contractFor(command: string): CommandContract | undefined {
  return CONTRACTS.find((c) => c.command === command);
}
